alias lr='ll -R'
alias lra='la -R'
#alias ss='~/.bin/session_search.sh '
alias ff='~/.bin/find_func.sh '
alias gg='egrep -R -I -n --color=auto * -e '
alias aa='~/.bin/around.sh '
alias h='history'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

export MINICOM="-c on -w"

export PATH="$PATH:${HOME}/.bin/"

